from Utils import Matriz

matriz = Matriz()

print(matriz.agregarUsuario("google", "ventas", "RT", "Ricardo Toca", "asdf123+"))
print(matriz.login("google", "entas", "RT", "asdf123+"))

matriz.agregarActivo("google", "ventas", "RT", "1asdf6", "Google Glass", "Lentes de Google")
print(matriz.activosUsuario("google", "ventas", "RT"))
matriz.agregarActivo("google", "ventas", "RT", "1hsgsd5", "Google Glass", "Lentes de Google")
print(matriz.activosUsuario("google", "ventas", "RT"))
matriz.agregarActivo("google", "ventas", "RT", "1dfhjwq4", "Google Glass", "Lentes de Google")
print(matriz.activosUsuario("google", "ventas", "RT"))
matriz.agregarActivo("google", "ventas", "RT", "1wrtuwf3", "Google Glass", "Lentes de Google")
print(matriz.activosUsuario("google", "ventas", "RT"))
matriz.agregarActivo("google", "ventas", "RT", "1jutrdh2", "Google Glass", "Lentes de Google")
print(matriz.activosUsuario("google", "ventas", "RT"))
matriz.agregarActivo("google", "ventas", "RT", "2dfgas", "Google Glass", "Lentes de Google")
print(matriz.activosUsuario("google", "ventas", "RT"))
matriz.agregarActivo("google", "ventas", "RT", "0ssdfs8", "Google Glass", "Lentes de Google")
print(matriz.activosUsuario("google", "ventas", "RT"))
matriz.agregarActivo("google", "ventas", "RT", "0asdf2sadf", "Google Glass", "Lentes de Google")
print(matriz.activosUsuario("google", "ventas", "RT"))
matriz.agregarActivo("google", "ventas", "RT", "0gsassdf", "Google Glass", "Lentes de Google")
print(matriz.activosUsuario("google", "ventas", "RT"))
matriz.agregarActivo("google", "ventas", "RT", "0fgjdd", "Google Glass", "Lentes de Google")
print(matriz.activosUsuario("google", "ventas", "RT"))
matriz.agregarActivo("google", "ventas", "RT", "0jerge", "Google Glass", "Lentes de Google")
print(matriz.activosUsuario("google", "ventas", "RT"))
matriz.agregarActivo("google", "ventas", "RT", "0jtyuf", "Google Glass", "Lentes de Google")
print(matriz.activosUsuario("google", "ventas", "RT"))
matriz.agregarActivo("google", "ventas", "RT", "0gsdfsdf", "Google Glass", "Lentes de Google")
print(matriz.activosUsuario("google", "ventas", "RT"))
matriz.agregarActivo("google", "ventas", "RT", "0gsasdfsdf", "Google Glass", "Lentes de Google")
print(matriz.activosUsuario("google", "ventas", "RT"))
matriz.agregarActivo("google", "ventas", "RT", "0gsashdfsdf", "Google Glass", "Lentes de Google")
print(matriz.activosUsuario("google", "ventas", "RT"))

